name: delivery
description: "Projeto de delivery"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.0.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banners/
    - assets/categories/
    - assets/dishes/
    - assets/others/
    - assets/restaurants/
